name: Market Report Automation

on:
  schedule:
    - cron: '0 3,15 * * 1-5'  # 05:00 & 17:00 SAST = 03:00 & 15:00 UTC
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pycoingecko

      - name: Run market report
        env:
          GITHUBACTIONS_PASSWORD: ${{ secrets.GITHUBACTIONS_PASSWORD }}
        run: python main.py

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create a temporary directory
          mkdir deploy_dir
          cp Market_Report.html feed.xml deploy_dir/

          # Switch to gh-pages branch (create if needed)
          git fetch origin
          git checkout gh-pages 2>/dev/null || git checkout --orphan gh-pages
          rm -rf *
          cp deploy_dir/* .

          git add .
          git commit -m "Update HTML and RSS" || echo "No changes to commit"
          git push origin gh-pages
