name: Market Report Automation

on:
  schedule:
    # 05:00 AM and 17:00 PM SAST = 03:00 and 15:00 UTC
    - cron: '0 3,15 * * 1-5'
  workflow_dispatch:  # allow manual runs

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pycoingecko

      - name: Run market report
        env:
          GITHUBACTIONS_PASSWORD: ${{ secrets.GITHUBACTIONS_PASSWORD }}
        run: |
          python main.py

      - name: Publish HTML and RSS to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin gh-pages || echo "No gh-pages branch yet"
          git checkout gh-pages || git checkout --orphan gh-pages
          cp Market_Report.html feed.xml .
          git add Market_Report.html feed.xml
          git commit -m "Update market report and RSS feed" || echo "No changes to commit"
          git push --force origin gh-pages
