name: Market Report Automation

on:
  schedule:
    # 05:00 AM and 17:00 PM SAST = 03:00 and 15:00 UTC
    - cron: '0 3,15 * * 1-5'
  workflow_dispatch:  # allow manual runs

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pycoingecko

      - name: Run market report
        run: |
          python main.py
