name: Market Report Automation

on:
  schedule:
    - cron: '0 3,15 * * 1-5'  # 05:00 & 17:00 SAST (03:00 & 15:00 UTC)
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pycoingecko

      - name: Run main.py to generate report and RSS
        env:
          GITHUBACTIONS_PASSWORD: ${{ secrets.GITHUBACTIONS_PASSWORD }}
        run: python main.py

      - name: Publish report to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin gh-pages || echo "No gh-pages branch yet"
          git switch gh-pages || git checkout --orphan gh-pages

          cp Market_Report.html feed.xml .

          git add Market_Report.html feed.xml
          git commit -m "Update Market Report and RSS feed" || echo "No changes to commit"
          git push origin gh-pages
